### ISSUE TITLE
Issue with 144 LED strip

### ISSUE THREAD

**Issue by 19eighties** [adafruit/Adafruit_DotStar#13]
If I try the library with lighting up all 144 LEDS, the last 2 are not light up correctly and seem delayed by a step. I confirmed this using an Arduino Uno and ESP8266. I switched to the FastLED library and the issue went away. 

```
uint16_t NUM_LEDS = 144;

uint32_t color = 0xFF0000;

for(byte i=0; i<3; i++){
      for(byte x=0;x<NUM_LEDS;x++)
      {
        strip.setPixelColor(x, color);    
     }
  
strip.show(); 

delay(1500);                        

if((color >>= 8) == 0)          //  Next color (R->G->B) ... past blue now?
    color = 0xFF0000;             //   Yes, reset to red
}
```

**Comment by amitkrkc** [comment]
I am also having similar problem. I have a dotstar disk with 255 LEDs. When I wanted to turn the LEDs individually, the LEDs from 0 to 183 worked. But, the rest of the LEDs did not work. I tried with FastLED too. The problem is still there.

**Comment by DevilWAH** [comment]
Hi I think this is an issue with end frame. If you look at the specs the end frame is to push the bits through the led strip. I had issues that if i only update led 1 - 30 for example and then send end frames using "1", it affect the rest of the strip as leds upstream from 30 can get strangley effected. 

I find it better to use "0" as the end frame, all it needs it the clock cycle and sending either 1 or 0 has the same effect. the difference is that sending "0's" you can do so after x number of LED's but if you use 1 you really need to write the whole LED strip before you do. 

the more LED in the strip the more end cycles you needs (numLED / 2). What you find happens if you dont send the correct amount is that the end LED do not get updated until the next update cycle when the new start and control frames are send, which means more cycles.

**Comment by PaintYourDragon** [comment]
Working OK here. End frame issue was fixed a while back, but it's possible the version number wasn't properly bumped. Check for version 1.0.2 and update when available.

The '183' issue sounds like a defective pixel, not library. Full disk lights up here. Unless you're on a Trinket (or other ATtiny85); not enough RAM for 255 pixels.
