### ISSUE TITLE
Add support for passing in non-default SPI

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_DotStar#48]
This was intentionally left out of #47 just to keep that PR as simple as possible, since it was a major conversion. With that PR now in place, can look at adding the ability to pass in a non-default SPI instance.

There is a semi-related PR #20. But that PR is based on the older non-BusIO version of the library.

**Comment by ladyada** [comment]
im ok with non-default SPI (you can just toss it right into the busio initializer) but def do not want SERCOM management ick :)

**Comment by digitalcircuit** [comment]
If the fix in ["show: Use BusIO SPI transactions to set clock freq" #49](https://github.com/adafruit/Adafruit_DotStar/pull/49 ) is merged, supporting passing in a non-default SPI might also provide a way to specify something other than 8 MHz SPI frequency, too - useful for long or short DotStar runs.

(Currently, the SPI clock frequency isn't being set correctly due to missing `beginTransaction()`/`endTransaction()` calls, so it can still be overridden the old way by doing a `beginTransaction()` outside the DotStar library before calling `show()`.)

**Comment by gigaj0ule** [comment]
I’m interested in making this happen, what would be your recommended path?

**Comment by PaintYourDragon** [comment]
Added in 1.2.2 (I’m really surprised this wasn’t already there…sorry!)

**Comment by digitalcircuit** [comment]
Thank you for adding this!

I did misunderstand how this would work - [contrary to my past assumption in this issue](https://github.com/adafruit/Adafruit_DotStar/issues/48#issuecomment-1153455262 ), passing in [a custom SPIClass](https://github.com/adafruit/ArduinoCore-samd/blob/0fd44a54b75f34b57a4e634257748e0ba46ab6ae/libraries/SPI/SPI.h#L115 ) does not appear provide a way to override the SPI frequency of 8 MHz ([`8000000` in `Adafruit_SPIDevice` constructor](https://github.com/adafruit/Adafruit_DotStar/blob/6b8287e96eb19bec79fb702d76597580cd44e113/Adafruit_DotStar.cpp#L59-L60 )).  This would help with long runs of DotStar LEDs (6 MHz is stable even with a voltage drop to 4 VDC, whereas 8 MHz requires closer to 4.5+ VDC).

Should I file a new, separate issue for a way to set the SPI frequency?
